// Package db will contain code generated by sqlc.
//
// Run `sqlc generate` (or `make generate`) to populate this package
// with type-safe Go functions derived from the SQL queries defined in
// sql/queries/.
//
// Do NOT write manual logic in this package — it is entirely managed
// by sqlc.
package db
